language: julia
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false
# sudo: false
before_install:
  - if [ `uname` = "Linux" ]; then
      sudo apt-get -qq update;
      sudo apt-get install -y ncbi-blast+;
    elif [ `uname` = "Darwin" ]; then
      brew tap homebrew/science;
      brew update;
      brew install blast;
    fi
before_script:
  - export PATH=$HOME/.local/bin:$PATH
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Bio"); Pkg.test("Bio"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Bio")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("Bio")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("Bio")); Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl"); include(joinpath("docs", "make.jl"))'
